---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the mysql packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: mysql_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install the mysql packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  with_items: mysql_pkgs
  environment: env
  when: ansible_os_family == 'Debian'

- name: Start the mysql services Redhat
  service: name={{ mysql_service }} state=started enabled=yes
